### ISSUE TITLE
Firefox displays Material Theme incorrectly 

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-core#100]
The material theme on Firefox is resulting in overflow.

Material theme:
![screen shot 2016-08-08 at 3 18 31 pm](https://cloud.githubusercontent.com/assets/768965/17498346/aaa3e2cc-5d7b-11e6-8f77-4fdc5412123d.png)

Default theme:
![screen shot 2016-08-08 at 3 18 39 pm](https://cloud.githubusercontent.com/assets/768965/17498354/b4e6e0b8-5d7b-11e6-8601-5fc6610293e5.png)

On changing the default padding prop on VictoryChart, it's alleviated, but I am not sure if this is the cause: 
![screen shot 2016-08-08 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/768965/17498420/1e869220-5d7c-11e6-9f7d-4b6aea747e7e.png)

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#338
