### ISSUE TITLE
Add labelAngle prop

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-core#16]
_From @boygirl on November 19, 2015 22:24_

This prop should rotate the label by some number of degrees starting at the exact x, y position (and whatever dx, dy)

_Copied from original issue: FormidableLabs/victory-label#7_

**Comment by boygirl** [comment]
_From @coopy on December 17, 2015 21:50_

Label should rotate around the specified `textAnchor`.

**Comment by cpb** [comment]
As I asked in https://github.com/FormidableLabs/victory-core/issues/37 -- what signature would you like for charting components use of the new label angle prop?
