### ISSUE TITLE
Passing additional information to child of VictoryAnimation

### ISSUE THREAD

**Issue by mathisonian** [FormidableLabs/victory-core#55]
Feature Request:

I am running into some cases where it would be very useful for the child of a `VictoryAnimation` component to know something about the state of the animation. In particular I'd like to be able to answer the questions:

* Is this component currently animating or not?
* If it is animating, what point are we at in the transition

A suggestion for how it could look, keeping things compatible with the current api

```js
<Victory.VictoryAnimation data={dataObj}>
  {
    (tweened, animationInfo) => {
      return (
         <Child />
      )
    }
  }
</Victory.VictoryAnimation>
```

**Comment by boygirl** [comment]
ETA 5/30 release

**Comment by bmathews** [comment]
Resolved via https://github.com/FormidableLabs/victory-core/pull/94, not yet released.
