### ISSUE TITLE
Animating Live Data

### ISSUE THREAD

**Issue by Mike-Dax** [FormidableLabs/victory-core#96]
This web page probably illustrates what I'm trying to achieve best:

https://bost.ocks.org/mike/path/

Is it possible to animate the transform of both the data point and the associated label in order to smoothly introduce new data points and remove the old? Or alternatively animate the domain itself?

I can set the domain based on my timed data and then manually rerender often, but I'm sure there must be a better way?

**Comment by boygirl** [comment]
@Mike-Dax you have incredible timing! We're working on this right now. I expect it to be released this week.

**Comment by boygirl** [comment]
@Mike-Dax There's an example up on the [victory site](https://formidable.com/open-source/victory/). The code for the example is [here](https://github.com/FormidableLabs/victory-docs/blob/master/src/screens/home/components/livechart.js)
